name: test
on:
    workflow_dispatch:
    push: {branches: ['main']}

concurrency:
    group: ci-${{ github.ref }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6
            -   name: composer
                uses: php-actions/composer@v6
                with:
                    dev: yes
                    php_version: '8.4'
                    memory_limit: 512M
                    args: '--no-ansi --no-scripts --no-progress -o'

            -   name: phpstan
                uses: php-actions/phpstan@v3
                with:
                    php_version: '8.4'
                    configuration: phpstan.dist.neon
                    memory_limit: 512M

            -   name: phpunit
                uses: php-actions/phpunit@v4
                with:
                    php_version: '8.4'
                    configuration: phpunit.xml.dist
                    memory_limit: '512M'
                    php_extensions: mbstring
