name: test
on:
    workflow_dispatch:
    push: {branches: ['main']}

concurrency:
    group: ci-${{ github.ref }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: composer
                uses: php-actions/composer@v6
                with:
                    dev: yes
                    php_version: '8.1'
                    memory_limit: 512M
                    args: '--ignore-platform-reqs --no-ansi --no-scripts --no-progress -o'

            -   name: phpunit
                uses: php-actions/phpunit@v3
                with:
                    version: '9.5'
                    php_version: '8.1'
                    configuration: phpunit.xml.dist
                    args: '--coverage-text -dxdebug.mode=coverage'
                    memory_limit: '512M'
                    php_extensions: xdebug mbstring
